<a href="https://colab.research.google.com/github/jasmidd/MSSP6070/blob/main/Assignments/Participation_Activity_Week4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
%run /content/drive/MyDrive/MSSP6070/Modules/Week04/Google_connection.py

Changed directory to: /content/MSSP6070/MSSP6070/MSSP6070

In [ ]:
import os

directory_path = '/content/drive/MyDrive/MSSP6070/Modules/Week04/'
if os.path.exists(directory_path):
    print(f"Contents of '{directory_path}':")
    for item in os.listdir(directory_path):
        print(item)
else:
    print(f"Directory '{directory_path}' does not exist.")

Contents of '/content/drive/MyDrive/MSSP6070/Modules/Week04/':
parsed.csv
Google_connection.py
Working_with_Pandas_DataFrames

In [ ]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/MSSP6070/Modules/Week04/parsed.csv')

2a.

In [ ]:
japan_mb = df[
    (df["parsed_place"] == "Japan") &
    (df["magType"] == "mb")
]
percentile_95 = japan_mb["mag"].quantile(0.95)
print(f"95th percentile of earthquake magnitude in Japan using magType of 'mb': \n{percentile_95}")

95th percentile of earthquake magnitude in Japan using magType of 'mb':
4.9

2b.

In [ ]:
indonesia_eq = df[
    (df["parsed_place"] == "Indonesia") &
    (df["type"] == "earthquake")
]
percentage_tsunami = ((indonesia_eq["tsunami"] == 1).sum()) / len(indonesia_eq) * 100
print(f"Percentage of earthquakes in Indonesia coupled with tsunanmis: \n{percentage_tsunami}")

Percentage of earthquakes in Indonesia coupled with tsunanmis:
23.12925170068027

2c.

In [ ]:
nevada_eq = df[
    (df["parsed_place"] == "Nevada") &
    (df["type"] == "earthquake")
]
nevada_eq.describe()

,cdi,dmin,felt,gap,mag,mmi,nst,rms,sig,time,tsunami,tz,updated
count,14.000000,647.000000,14.000000,647.000000,647.000000,1.00,647.000000,647.000000,647.000000,6.470000e+02,647.0,647.0,6.470000e+02
mean,2.421429,0.163155,2.500000,154.436615,0.437311,2.84,12.704791,0.140627,9.146832,1.538318e+12,0.0,-480.0,1.538409e+12
std,0.514675,0.161793,4.783787,69.474945,0.653397,NaN,10.052695,0.056765,17.939055,5.954980e+08,0.0,0.0,5.991682e+08
min,2.000000,0.001000,1.000000,29.140000,-0.500000,2.84,3.000000,0.000500,0.000000,1.537247e+12,0.0,-480.0,1.537323e+12
25%,2.000000,0.053000,1.000000,97.295000,-0.100000,2.84,6.000000,0.104400,0.000000,1.537859e+12,0.0,-480.0,1.537928e+12
50%,2.200000,0.109000,1.000000,150.040000,0.300000,2.84,9.000000,0.142900,1.000000,1.538286e+12,0.0,-480.0,1.538428e+12
75%,3.000000,0.223000,1.000000,200.515000,0.800000,2.84,16.000000,0.181050,10.000000,1.538824e+12,0.0,-480.0,1.538878e+12
max,3.300000,1.414000,19.000000,355.910000,2.900000,2.84,61.000000,0.340000,129.000000,1.539461e+12,0.0,-480.0,1.539483e+12

2d.

In [ ]:
df["ring_of_fire"] = ''
df.columns
df["ring_of_fire"] = df["parsed_place"].str.contains(r'|'.join([
    "Bolivia", "Chile", "Ecuador", "Peru", "Costa Rica", "Guatemala", "^Mexico", "Japan", "Philippines",
    "Indonesia", "New Zealand", "Antarctic", "Canada", "Fiji", "Alaska", "Washington", "California",
    "Russia", "Taiwan", "Tonga", "Kermadec Islands"
]))
df[["ring_of_fire", "parsed_place"]]

      ring_of_fire parsed_place
0             True   California
1             True   California
2             True   California
3             True   California
4             True   California
...            ...          ...
9327          True   California
9328          True   California
9329         False  Puerto Rico
9330          True   California
9331          True   California

[9332 rows x 2 columns]

2e.

In [ ]:
df["ring_of_fire"].value_counts()
display(df["ring_of_fire"].value_counts())

ring_of_fire
True     7188
False    2144
Name: count, dtype: int64

2f.

In [ ]:
tsunami_count = df[
    (df["ring_of_fire"]) &
    (df["tsunami"] == 1)
]
print(f"Tsunami count along the Ring of Fire: \n{len(tsunami_count)}")

Tsunami count along the Ring of Fire:
45